Hw03 mongodb
tskalska/nodejs-homework-rest-api pull request #2
Opened 2022-02-13 19:09 UTC by tskalska

For review

2022-02-14 18:53 UTC, KirillKulakow commented on .env
> +DB_HOST=mongodb+srv://Skate:CKhJ5e7cy1eKZIcr@cluster0.beqzf.mongodb.net/db-contacts?retryWrites=true&w=majority
удалить этот файл
доступы к базам данных не должны хранится в открытом доступе
сам файл добавить в gitignore

2022-02-14 19:01 UTC, KirillKulakow commented on routes/api/contacts.js
> +  const{contactId}=req.params;
идентификаторы документов в много дб имеют одинаковую типизацию
это строка из 24 символов с числами от 0 до 9 и буквами от a до f (маленькие), сам ид похож на HEX цвет в CSS только длинней
Суть в том что если ид будет не валидный у тебя будет ошибка в приложении
сделай проверку перед запросом в Базу данных
есть метод Mongoose.Types.ObjectId.isValid

2022-02-14 19:02 UTC, KirillKulakow commented on routes/api/contacts.js
> +  const{contactId}=req.params;
сделай проверку, описал в прошлом комменте

2022-02-14 19:02 UTC, KirillKulakow commented on routes/api/contacts.js
> +  const {contactId} = req.params;
сделай проверку, описал в прошлом комменте

2022-02-14 19:03 UTC, KirillKulakow commented on routes/api/contacts.js
>    const {contactId} = req.params;
сделай проверку, описал в прошлом комменте

2022-02-14 19:03 UTC, KirillKulakow commented
удали также файл .DS_Store + добавь в gitignore

2022-02-14 19:03 UTC, KirillKulakow requested changes
need fix

2022-02-14 22:29 UTC, tskalska commented
Поправила

2022-02-15 20:24 UTC, KirillKulakow commented on routes/api/contacts.js
>    const {contactId} = req.params;
добавь проверку

2022-02-15 20:25 UTC, KirillKulakow approved these changes

2022-02-15 21:10 UTC, merged