Home work 4
tskalska/nodejs-homework-rest-api pull request #3
Opened 2022-02-19 12:49 UTC by tskalska

Здравствуйте, 4 дз готово.

2022-02-20 09:26 UTC, KirillKulakow commented on controllers/auth/login.js
> +            const compareResult = await bcrypt.compare(password, user.password);
а если пользователь не найден, а ты ищешь пароль в юзере

2022-02-20 09:27 UTC, KirillKulakow commented on controllers/auth/login.js
> +const signup = async (req, res, next)=> {
переименуй функцию

2022-02-20 09:33 UTC, KirillKulakow commented on routes/api/contacts.js
> +router.patch("/:contactId/favorite", changeFavorite);
почему удаление изменение контакта без аутентификации?

2022-02-20 09:34 UTC, KirillKulakow commented on controllers/contacts/getById.js
> +    const contact = await Contact.findById(contactId);
на данный момент любой юзер может посмотреть контакт другого юзера, зная ид контакта
используй поле owner и делай поискан в том числе и по этому ключу

2022-02-20 09:34 UTC, KirillKulakow commented on controllers/contacts/deleteById.js
> +    const newContacts = await Contact.findByIdAndDelete(contactId);
на данный момент любой юзер может удалить контакт другого юзера, зная ид контакта
используй поле owner и делай поискан в том числе и по этому ключу

2022-02-20 09:34 UTC, KirillKulakow commented on controllers/contacts/changeFavorite.js
> +    const newContact = await Contact.findByIdAndUpdate(contactId, req.body, {new:true});
на данный момент любой юзер может изменить контакт другого юзера, зная ид контакта
используй поле owner и делай поискан в том числе и по этому ключу

2022-02-20 09:34 UTC, KirillKulakow commented on controllers/contacts/changeContact.js
> +      const updateContact = await Contact.findByIdAndUpdate(contactId, body);
на данный момент любой юзер может посмотреть контакт другого юзера, зная ид контакта
используй поле owner и делай поискан в том числе и по этому ключу

2022-02-20 09:35 UTC, KirillKulakow requested changes
Need fix

2022-02-20 20:14 UTC, tskalska commented
fixes done

2022-02-21 08:29 UTC, KirillKulakow approved these changes

2022-02-21 18:49 UTC, merged